---
- name: Install dependencies
  become: true
  apt:
    name: 
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Add HashiCorp GPG key
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install Vagrant
  become: true
  apt:
    name: vagrant
    state: present

