---
- name: Install dependencies
  apt:
    name: 
      - wget
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Add HashiCorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/vagrant.asc
    mode: '0644'

- name: Add HashiCorp repository
  ansible.builtin.command: |
    echo "deb [signed-by=/etc/apt/keyrings/vagrant.asc] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  args:
    creates: /etc/apt/sources.list.d/hashicorp.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Vagrant
  apt:
    name: vagrant
    state: present

