---
- name: Install Rust programming language
  become: false
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: /home/{{ ansible_user }}/.cargo/bin/rustc
    executable: /bin/bash

# - name: Add Rust to the PATH environment variable
#   become: false
#   ansible.builtin.copy:
#     content: 'export PATH="$HOME/.cargo/bin:$PATH"'
#     dest: ~/.profile
#     owner: "{{ ansible_user }}"
#     mode: '0644'
#   notify: Refresh shell environment

- name: Ensure Rust is in the PATH environment variable
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.profile"
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    insertafter: EOF
    owner: "{{ ansible_user }}"
    mode: '0644'
  notify: Refresh shell environment
